<?php

/**
 * Copyright since 2007 PrestaShop SA and Contributors
 * PrestaShop is an International Registered Trademark & Property of PrestaShop SA.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License version 3.0
 * that is bundled with this package in the file LICENSE.md.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/AFL-3.0
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@prestashop.com so we can send you a copy immediately.
 *
 * @author    Massimiliano Palermo <maxx.palermo@gmail.com>
 * @copyright Since 2016 Massimiliano Palermo
 * @license   https://opensource.org/licenses/AFL-3.0 Academic Free License version 3.0
 */

namespace MpSoft\MpBrtApiShipment\Config;

class BrtEasySped
{
    public function getVabParams()
    {
        $easyspedFields = [
            'VABATB' => [
                'description' => 'NETWORK SPEDIZIONI ESTERO',
                'type' => 'A',
                'length' => 1,
                'decimals' => 0,
                'start' => 1,
                'end' => 1,
                'mandatory' => false,
            ],
            'VABCCM' => [
                'description' => 'CODICE CLIENTE MITTENTE',
                'type' => 'S',
                'length' => 7,
                'decimals' => 0,
                'start' => 2,
                'end' => 9,
                'mandatory' => true,
            ],
            'VABLNP' => [
                'description' => 'P.OPER. PARTENZA',
                'type' => 'S',
                'length' => 3,
                'decimals' => 0,
                'start' => 10,
                'end' => 13,
                'mandatory' => false,
            ],
            'VABAAS' => [
                'description' => 'ANNO SPEDIZIONE',
                'type' => 'S',
                'length' => 4,
                'decimals' => 0,
                'start' => 14,
                'end' => 18,
                'mandatory' => false,
            ],
            'VABMGS' => [
                'description' => 'MESE/GIORNO SPEDIZIONE',
                'type' => 'S',
                'length' => 4,
                'decimals' => 0,
                'start' => 19,
                'end' => 23,
                'mandatory' => false,
            ],
            'VABNRS' => [
                'description' => 'NUMERO SERIE',
                'type' => 'S',
                'length' => 2,
                'decimals' => 0,
                'start' => 24,
                'end' => 26,
                'mandatory' => false,
            ],
            'VABNSP' => [
                'description' => 'NUMERO SPEDIZIONE',
                'type' => 'S',
                'length' => 7,
                'decimals' => 0,
                'start' => 27,
                'end' => 34,
                'mandatory' => false,
            ],
            'VABCBO' => [
                'description' => 'CODICE BOLLA',
                'type' => 'A',
                'length' => 2,
                'decimals' => 0,
                'start' => 35,
                'end' => 36,
                'mandatory' => true,
                'table' => [
                    '1' => 'FRANCO',
                    '2' => 'ASSEGNATO',
                    '4' => 'FRANCO +C/ASSEGNO',
                    '6' => 'ASSEGNATO +C/ASSEGNO',
                ],
            ],
            'VABLNA' => [
                'description' => 'P.OPER. ARRIVO',
                'type' => 'S',
                'length' => 3,
                'decimals' => 0,
                'start' => 37,
                'end' => 40,
                'mandatory' => false,
            ],
            'VABRSD' => [
                'description' => 'RAGIONE SOCIALE DESTINATARIO',
                'type' => 'A',
                'length' => 35,
                'decimals' => 0,
                'start' => 41,
                'end' => 75,
                'mandatory' => true,
            ],
            'VABRD2' => [
                'description' => 'ESTENSIONE RAG.SOC.DESTINATARIO',
                'type' => 'A',
                'length' => 35,
                'decimals' => 0,
                'start' => 76,
                'end' => 110,
                'mandatory' => false,
            ],
            'VABIND' => [
                'description' => 'INDIRIZZO DESTINATARIO',
                'type' => 'A',
                'length' => 35,
                'decimals' => 0,
                'start' => 111,
                'end' => 145,
                'mandatory' => true,
            ],
            'VABCAD' => [
                'description' => 'CAP DESTINATARIO',
                'type' => 'A',
                'length' => 9,
                'decimals' => 0,
                'start' => 146,
                'end' => 154,
                'mandatory' => true,
            ],
            'VABLOD' => [
                'description' => 'LOCALITA DESTINATARIO',
                'type' => 'A',
                'length' => 35,
                'decimals' => 0,
                'start' => 155,
                'end' => 189,
                'mandatory' => true,
            ],
            'VABPRD' => [
                'description' => 'PROVINCIA DESTINATARIO',
                'type' => 'A',
                'length' => 2,
                'decimals' => 0,
                'start' => 190,
                'end' => 191,
                'mandatory' => true,
            ],
            'VABNZD' => [
                'description' => 'NAZIONE DESTINATARIO',
                'type' => 'A',
                'length' => 3,
                'decimals' => 0,
                'start' => 192,
                'end' => 194,
                'mandatory' => true,
            ],
            'VABGC1' => [
                'description' => '1° GG.CHIUSURA DESTINATARIO',
                'type' => 'A',
                'length' => 2,
                'decimals' => 0,
                'start' => 195,
                'end' => 196,
                'mandatory' => false,
            ],
            'VABGC2' => [
                'description' => '2° GG.CHIUSURA DESTINATARIO',
                'type' => 'A',
                'length' => 2,
                'decimals' => 0,
                'start' => 197,
                'end' => 198,
                'mandatory' => false,
            ],
            'VABCTR' => [
                'description' => 'CODICE TARIFFA',
                'type' => 'S',
                'length' => 3,
                'decimals' => 0,
                'start' => 199,
                'end' => 201,
                'mandatory' => false,
            ],
            'VABTSP' => [
                'description' => 'TIPO SERVIZIO BOLLE',
                'type' => 'A',
                'length' => 1,
                'decimals' => 0,
                'start' => 203,
                'end' => 203,
                'mandatory' => false,
                'params' => [
                    'C' => 'Servizio Corriere',
                    'E' => 'Servizio Priority',
                    'H' => 'Servizio 10:30',
                ],
            ],
            'VABIAS' => [
                'description' => 'IMPORTO DA ASSICURARE',
                'type' => 'S',
                'length' => 13,
                'decimals' => 3,
                'start' => 204,
                'end' => 218,
                'mandatory' => false,
                'regex' => '/^ \d{10},\d{3}$/',
            ],
            'VABVAS' => [
                'description' => 'DIVISA IMPORTO DA ASSICURARE',
                'type' => 'A',
                'length' => 3,
                'decimals' => 0,
                'start' => 219,
                'end' => 221,
                'mandatory' => false,
            ],
            'VABNAS' => [
                'description' => 'NATURA MERCE MITTENTE',
                'type' => 'A',
                'length' => 15,
                'decimals' => 0,
                'start' => 222,
                'end' => 236,
                'mandatory' => false,
            ],
            'VABNCL' => [
                'description' => 'NUMERO COLLI',
                'type' => 'S',
                'length' => 5,
                'decimals' => 0,
                'start' => 237,
                'end' => 242,
                'mandatory' => true,
            ],
            'VABPKB' => [
                'description' => 'PESO KG BOLLETTATO',
                'type' => 'S',
                'length' => 7,
                'decimals' => 1,
                'start' => 243,
                'end' => 251,
                'mandatory' => true,
                'regex' => '/^ \d{6},\d{1}$/',
            ],
            'VABVLB' => [
                'description' => 'VOLUME BOLLETTATO',
                'type' => 'S',
                'length' => 5,
                'decimals' => 3,
                'start' => 252,
                'end' => 258,
                'mandatory' => false,
                'regex' => '/^ \d{2},\d{3}$/',
            ],
            'VABQFT' => [
                'description' => 'QUANTITA DA FATTURARE',
                'type' => 'S',
                'length' => 13,
                'decimals' => 3,
                'start' => 259,
                'end' => 273,
                'mandatory' => false,
                'regex' => '/^ \d{10},\d{3}$/',
            ],
            'VABCAS' => [
                'description' => 'CONTRASSEGNO',
                'type' => 'S',
                'length' => 13,
                'decimals' => 3,
                'start' => 274,
                'end' => 288,
                'mandatory' => false,
                'regex' => '/^ \d{10},\d{3}$/',
            ],
            'VABTIC' => [
                'description' => 'TIPO INCASSO CONTRASS.',
                'type' => 'A',
                'length' => 2,
                'decimals' => 0,
                'start' => 289,
                'end' => 291,
                'mandatory' => false,
                'table' => [
                    'BM' => 'ACCETTARE ASSEGNO BANCARIO INTESTATO ALLA MITTENTE',
                    'CM' => 'ACCETTARE ASSEGNO CIRCOLARE INTESTATO ALLA MITTENTE',
                    'BB' => 'ACCETTARE ASSEGNO BANCARIO INTESTATO CORRIERE CON MANLEVA',
                    'OM' => 'ACCETTARE ASSEGNO INTESTATO AL MITTENTE ORIGINALE',
                    'OC' => 'ACCETTARE ASSEGNO CIRCOLARE INTESTATO AL MITTENTE ORIGINALE',
                    '' => 'ACCETTARE CONTANTE',
                ],
            ],
            'VABVCA' => [
                'description' => 'DIVISA IMPORTO C/ASSEGNO',
                'type' => 'A',
                'length' => 3,
                'decimals' => 0,
                'start' => 291,
                'end' => 293,
                'mandatory' => false,
                'table' => [
                    'CHF' => 'Franco Svizzero',
                    'DKK' => 'Corona Danese',
                    'EUR' => 'Euro',
                    'GBP' => 'Sterlina Inglese',
                    'NDK' => 'Corona Norvegese',
                    'SEK' => 'Corona Svedese',
                    'USD' => 'Dollaro USA',
                ],
            ],
            'VABGCA' => [
                'description' => 'GESTIONE PARTICOLARITA C/A',
                'type' => 'A',
                'length' => 2,
                'decimals' => 0,
                'start' => 294,
                'end' => 295,
                'mandatory' => false,
                'table' => [
                    'BM' => 'ACCETTARE ASSEGNO BANCARIO INTESTATO ALLA MITTENTE',
                    'CM' => 'ACCETTARE ASSEGNO CIRCOLARE INTESTATO ALLA MITTENTE',
                    'BB' => 'ACCETTARE ASSEGNO BANCARIO INTESTATO CORRIERE CON MANLEVA',
                    'OM' => 'ACCETTARE ASSEGNO INTESTATO AL MITTENTE ORIGINALE',
                    'OC' => 'ACCETTARE ASSEGNO CIRCOLARE INTESTATO AL MITTENTE ORIGINALE',
                    '' => 'ACCETTARE CONTANTE',
                ],
            ],
            'VABRMN' => [
                'description' => 'RIFERIM.MITTENTE NUMERICO',
                'type' => 'S',
                'length' => 15,
                'decimals' => 0,
                'start' => 296,
                'end' => 311,
                'mandatory' => true,
            ],
            'VABRMA' => [
                'description' => 'RIFERIM.MITTENTE ALFABETICO',
                'type' => 'A',
                'length' => 15,
                'decimals' => 0,
                'start' => 312,
                'end' => 326,
                'mandatory' => false,
            ],
            'VABNCD' => [
                'description' => 'NUM SEGNACOLLO DAL',
                'type' => 'S',
                'length' => 7,
                'decimals' => 0,
                'start' => 327,
                'end' => 334,
                'mandatory' => false,
            ],
            'VABNCA' => [
                'description' => 'NUM SEGNACOLLO AL',
                'type' => 'S',
                'length' => 7,
                'decimals' => 0,
                'start' => 335,
                'end' => 342,
                'mandatory' => false,
            ],
            'VABXCO' => [
                'description' => 'X = CUMULATIVO COLLI',
                'type' => 'A',
                'length' => 1,
                'decimals' => 0,
                'start' => 343,
                'end' => 343,
                'mandatory' => false,
                'params' => [
                    'X' => '',
                ],
            ],
            'VABNOT' => [
                'description' => 'DESCRIZIONE/NOTE',
                'type' => 'A',
                'length' => 35,
                'decimals' => 0,
                'start' => 344,
                'end' => 378,
                'mandatory' => false,
            ],
            'VABNT2' => [
                'description' => 'DESCRIZIONE/NOTE AGGIUNTIVE',
                'type' => 'A',
                'length' => 35,
                'decimals' => 0,
                'start' => 379,
                'end' => 413,
                'mandatory' => false,
            ],
            'VABZNC' => [
                'description' => 'ZONA CONSEGNA',
                'type' => 'A',
                'length' => 2,
                'decimals' => 0,
                'start' => 414,
                'end' => 416,
                'mandatory' => false,
            ],
            'VABCTM' => [
                'description' => 'COD.TRATTAMENTO MERCE',
                'type' => 'A',
                'length' => 2,
                'decimals' => 0,
                'start' => 417,
                'end' => 418,
                'mandatory' => false,
                'table' => [
                    ' ' => 'Soluzione A',
                    '7A' => 'Soluzione A con FNVAX00R spedizioni non gestite con Disk C BRT',
                    '7J' => 'Soluzione A con FNVAX00R spedizioni gestite con Disk C BRT',
                    'DT' => 'Soluzione A2',
                    '2 ' => 'Soluzione B',
                    '2A' => 'Soluzione B con FNVAX00R',
                    '2D' => 'Soluzione B2',
                    '2E' => 'Soluzione B2 con FNVAX00R',
                    '7Q' => 'Soluzione C',
                    '7T' => 'Soluzione C con FNVAX00R',
                ],
            ],
            'VABFFD' => [
                'description' => 'S = FERMO DEPOSITO',
                'type' => 'A',
                'length' => 1,
                'decimals' => 0,
                'start' => 419,
                'end' => 419,
                'mandatory' => false,
                'params' => [
                    'S' => 'S||',
                ],
            ],
            'VABDCR' => [
                'description' => 'DATA CONSEGNA RICHIESTA',
                'type' => 'S',
                'length' => 8,
                'decimals' => 0,
                'start' => 420,
                'end' => 428,
                'mandatory' => false,
                'regex' => '/^\d{8}$/',
                'params' => [
                    'DATE_FORMAT' => 'YYYYMMDD',
                ],
            ],
            'VABTCR' => [
                'description' => 'TIPO CONS.',
                'type' => 'A',
                'length' => 1,
                'decimals' => 0,
                'start' => 429,
                'end' => 429,
                'mandatory' => false,
                'table' => [
                    '' => 'Consegna default',
                    'P' => 'Consegna prima del',
                    'D' => 'Consegna dopo il',
                ],
            ],
            'VABHCR' => [
                'description' => 'ORA CONSEGNA RICHIESTA',
                'type' => 'A',
                'length' => 4,
                'decimals' => 0,
                'start' => 430,
                'end' => 434,
                'mandatory' => false,
            ],
            'VABCTS' => [
                'description' => 'T = CODICE TASSAZIONE',
                'type' => 'A',
                'length' => 2,
                'decimals' => 0,
                'start' => 435,
                'end' => 436,
                'mandatory' => false,
                'params' => [
                    'T' => '',
                ],
            ],
            'VABFTM' => [
                'description' => 'S = FLAG TASSAZIONE C/TARIFFA MITTENTE',
                'type' => 'A',
                'length' => 1,
                'decimals' => 0,
                'start' => 437,
                'end' => 437,
                'mandatory' => false,
                'params' => [
                    'S' => 'S||',
                ],
            ],
            'VABVMD' => [
                'description' => 'VALORE MERCE DICHIARATO',
                'type' => 'S',
                'length' => 13,
                'decimals' => 3,
                'start' => 438,
                'end' => 452,
                'mandatory' => false,
                'regex' => '/^\d{10}\.\d{3}$/',
            ],
            'VABVAD' => [
                'description' => 'DIVISA VALORE MERCE DICHIARATO',
                'type' => 'A',
                'length' => 3,
                'decimals' => 0,
                'start' => 453,
                'end' => 455,
                'mandatory' => false,
                'table' => [
                    'CHF' => 'Franco Svizzero',
                    'DKK' => 'Corona Danese',
                    'EUR' => 'Euro',
                    'GBP' => 'Sterlina Inglese',
                    'NDK' => 'Corona Norvegese',
                    'SEK' => 'Corona Svedese',
                    'USD' => 'Dollaro USA',
                ],
            ],
            'VABGMA' => [
                'description' => 'GESTIONE PARTICOLARITA CONSEGNA',
                'type' => 'A',
                'length' => 2,
                'decimals' => 0,
                'start' => 456,
                'end' => 457,
                'mandatory' => false,
            ],
            'VABGGA' => [
                'description' => 'GESTIONE PARTICOLARITA GIACENZA',
                'type' => 'A',
                'length' => 2,
                'decimals' => 0,
                'start' => 458,
                'end' => 459,
                'mandatory' => false,
            ],
            'VABGVA' => [
                'description' => 'GESTIONE PARTICOLARITA\' VARIE',
                'type' => 'A',
                'length' => 2,
                'decimals' => 0,
                'start' => 460,
                'end' => 461,
                'mandatory' => false,
            ],
            'VABTC1' => [
                'description' => '1° CONSEGNA PARTICOLARE',
                'type' => 'A',
                'length' => 1,
                'decimals' => 0,
                'start' => 462,
                'end' => 462,
                'mandatory' => false,
                'table' => [
                    'A' => 'PER APPUNTAMENTO',
                    'F' => 'FUORI MISURA',
                    'P' => 'AI PIANI',
                    'S' => 'SUPERMERCATI',
                    'X' => 'CONSEGNA DESTINATARIO DISAGIATO',
                ],
            ],
            'VABTC2' => [
                'description' => '2° CONSEGNA PARTICOLARE',
                'type' => 'A',
                'length' => 1,
                'decimals' => 0,
                'start' => 463,
                'end' => 463,
                'mandatory' => false,
                'table' => [
                    'A' => 'PER APPUNTAMENTO',
                    'F' => 'FUORI MISURA',
                    'P' => 'AI PIANI',
                    'S' => 'SUPERMERCATI',
                    'X' => 'CONSEGNA DESTINATARIO DISAGIATO',
                ],
            ],
            'VABSCL' => [
                'description' => 'X = CODICE SOCIALE',
                'type' => 'A',
                'length' => 1,
                'decimals' => 0,
                'start' => 464,
                'end' => 464,
                'mandatory' => false,
                'params' => [
                    'X' => '',
                ],
            ],
            'VABANT' => [
                'description' => 'TIPO E QUANTITA’ BANCALI',
                'type' => 'S',
                'length' => 9,
                'decimals' => 0,
                'start' => 465,
                'end' => 474,
                'mandatory' => false,
                'params' => [
                    'tipo_bancali' => [
                        '01' => 'EUR',
                        '02' => 'EPAL',
                    ],
                    'composizione' => [
                        'POS01' => 'tipo_bancale',
                        'POS23' => 'tot_bancali',
                        'POS45' => 'tipo_bancale',
                        'POS67' => 'tot_bancali',
                        'POS8' => 'BLANK',
                    ],
                ],
            ],
            'VABRMO' => [
                'description' => 'RAG.SOC.MITTENTE ORIGINALE',
                'type' => 'A',
                'length' => 25,
                'decimals' => 0,
                'start' => 475,
                'end' => 499,
                'mandatory' => false,
            ],
            'VABCMO' => [
                'description' => 'C.A.P. MITTENTE ORIGINALE',
                'type' => 'A',
                'length' => 9,
                'decimals' => 0,
                'start' => 500,
                'end' => 508,
                'mandatory' => false,
            ],
            'VABNMO' => [
                'description' => 'NAZIONE MITTENTE ORIGINALE',
                'type' => 'A',
                'length' => 3,
                'decimals' => 0,
                'start' => 509,
                'end' => 511,
                'mandatory' => false,
                'table' => [
                    'IT' => 'Italia',
                    'A' => 'Austria',
                    'AND' => 'Andorra',
                    'B' => 'Belgio',
                    'BG' => 'Bulgaria',
                    'CH' => 'Svizzera',
                    'CZ' => 'Repubblica Ceca',
                    'D' => 'Germania',
                    'DK' => 'Danimarca',
                    'E' => 'Spagna',
                    'F' => 'Francia',
                    'GB' => 'Gran Bretagna',
                    'GBZ' => 'Gibilterra',
                    'HU' => 'Ungheria',
                    'IRL' => 'Irlanda',
                    'L' => 'Lussemburgo',
                    'LI' => 'Liechtenstein',
                    'MC' => 'Principato Monaco',
                    'NL' => 'Olanda',
                    'P' => 'Portogallo',
                    'PL' => 'Polonia',
                    'RO' => 'Romania',
                    'S' => 'Svezia',
                    'SK' => 'Slovacchia',
                    'SLO' => 'Slovenia',
                ],
            ],
            'VABNRC' => [
                'description' => 'NOME REFERENTE DESTINATARIO',
                'type' => 'A',
                'length' => 35,
                'decimals' => 0,
                'start' => 512,
                'end' => 546,
                'mandatory' => false,
            ],
            'VABTRC' => [
                'description' => 'TELEFONO REFERENTE DESTINATARIO',
                'type' => 'A',
                'length' => 16,
                'decimals' => 0,
                'start' => 513,
                'end' => 528,
                'mandatory' => false,
            ],
            'VABXXX' => [
                'description' => 'IMPOSTARE 4 SPAZI',
                'type' => 'S',
                'length' => 4,
                'decimals' => 0,
                'start' => 563,
                'end' => 566,
                'mandatory' => false,
                'params' => [
                    'BLANK' => '/\s{4}/',
                ],
            ],
            'VABEMD' => [
                'description' => 'INDIRIZZO EMAIL DESTINATARIO',
                'type' => 'A',
                'length' => 70,
                'decimals' => 0,
                'start' => 567,
                'end' => 636,
                'mandatory' => false,
                'params' => [
                    'SEPARATOR' => '|',
                ],
            ],
            'VABCEL' => [
                'description' => 'NUMERO CELLULARE PER SMS',
                'type' => 'A',
                'length' => 16,
                'decimals' => 0,
                'start' => 637,
                'end' => 652,
                'mandatory' => false,
                'params' => [
                    'FORMAT' => '/^\+\d{2}\d{1,10}$/',
                ],
            ],
            'VABTNO' => [
                'description' => 'TIPO NOTIFICA',
                'type' => 'A',
                'length' => 16,
                'decimals' => 0,
                'start' => 653,
                'end' => 668,
                'mandatory' => false,
                'params' => [
                    '0' => 'NESSUNA',
                    '1' => 'EMAIL',
                    '2' => 'SMS',
                    '3' => 'SMS+EMAIL',
                ],
            ],
        ];

        return $easyspedFields;
    }
}
