<?php

/**
 * Copyright since 2007 PrestaShop SA and Contributors
 * PrestaShop is an International Registered Trademark & Property of PrestaShop SA.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License version 3.0
 * that is bundled with this package in the file LICENSE.md.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/AFL-3.0
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@prestashop.com so we can send you a copy immediately.
 *
 * @author    Massimiliano Palermo <maxx.palermo@gmail.com>
 * @copyright Since 2016 Massimiliano Palermo
 * @license   https://opensource.org/licenses/AFL-3.0 Academic Free License version 3.0
 */

namespace MpSoft\MpBrtApiShipment\Config;

class CreateParams
{
    public static function getParams()
    {
        $brtFields = [
            'userID' => [
                'dato_obbligatorio' => true,
                'mandatory_if' => '',
                'rif_brt_vab' => '',
                'max_length' => '',
                'precision' => '',
                'scale' => '',
                'description' => "Codice utente per l'autenticazione al servizio. Dato obbligatorio.",
            ],
            'password' => [
                'dato_obbligatorio' => true,
                'mandatory_if' => '',
                'rif_brt_vab' => '',
                'max_length' => '',
                'precision' => '',
                'scale' => '',
                'description' => 'Password utente. Dato obbligatorio.',
            ],
            'network' => [
                'dato_obbligatorio' => false,
                'mandatory_if' => '',
                'rif_brt_vab' => 'VABATB',
                'max_length' => '1',
                'precision' => '',
                'scale' => '',
                'description' => "Network. [rif. BRT VABATB] [max length =1]\nI valori possibili vengono comunicati da BRT. Se indicata stringa vuota viene utilizzato il network standard BRT. In caso che il cliente possa scegliere più network, in ogni singola richiesta può essere indicato un solo valore. Viene controllata l'esistenza del dato e l'appartenenza al cliente.",
            ],
            'departureDepot' => [
                'dato_obbligatorio' => true,
                'mandatory_if' => '',
                'rif_brt_vab' => 'VABFGS',
                'max_length' => '',
                'precision' => '3',
                'scale' => '0',
                'description' => "Linea di partenza. [rif. BRT VABFGS] [precision  =3 scale=0]\nDato obbligatorio. Viene comunicato da BRT. In caso che il cliente abbia più punti di partenza, saranno comunicati più valori. In ogni singola richiesta può essere indicato un solo valore. Viene controllata l'esistenza del dato.",
            ],
            'senderCustomerCode' => [
                'dato_obbligatorio' => true,
                'mandatory_if' => '',
                'rif_brt_vab' => 'VABCCM',
                'max_length' => '',
                'precision' => '7',
                'scale' => '0',
                'description' => "Codice cliente mittente. [rif. BRT VABCCM] [precision  =7 scale=0]\nDato obbligatorio. Viene comunicato da BRT. In caso che il cliente abbia più codice cliente, saranno comunicati più valori. In ogni singola richiesta può essere indicato un solo valore. Viene controllata l'esistenza del dato e l'appartenenza all'utente di collegamento (legame padre-figlio).",
            ],
            'deliveryFreightTypeCode' => [
                'dato_obbligatorio' => true,
                'mandatory_if' => '',
                'rif_brt_vab' => 'VABCBO',
                'max_length' => '3',
                'precision' => '',
                'scale' => '',
                'description' => "Tipo porto. [rif. BRT VABCBO] [max length =3]\nDato obbligatorio. Può valere 'DAP' (porto franco) oppure 'EXW' (porto assegnato).",
            ],
            'consigneeCompanyName' => [
                'dato_obbligatorio' => false,
                'mandatory_if' => 'brtServiceCode non è B15',
                'rif_brt_vab' => 'VABRSD VABRD2',
                'max_length' => '70',
                'precision' => '',
                'scale' => '',
                'description' => "Ragione sociale destinatario. [rif. BRT VABRSD VABRD2] [max length =70]\nDato obbligatorio se brtServiceCode non è B15.",
            ],
            'consigneeAddress' => [
                'dato_obbligatorio' => false,
                'mandatory_if' => 'brtServiceCode non è B15',
                'rif_brt_vab' => '',
                'max_length' => '35/105',
                'precision' => '',
                'scale' => '',
                'description' => "Indirizzo destinatario. [min length = 6; max length =35 per spedizioni domestiche (IT) oppure effettuate con Network non abilitati alla gestione dell’indirizzo esteso, max length =105 per spedizioni estere effettuate con Network abilitati alla gestione dell’indirizzo esteso]\nDato obbligatorio se brtServiceCode non è B15.",
            ],
            'consigneeZIPCode' => [
                'dato_obbligatorio' => false,
                'mandatory_if' => 'brtServiceCode non è B15',
                'rif_brt_vab' => 'VABCAD',
                'max_length' => '9',
                'precision' => '',
                'scale' => '',
                'description' => "CAP nel formato della nazione di destinazione. [rif. BRT VABCAD] [max length =9]\nDato obbligatorio se brtServiceCode non è B15. Viene controllato che sia formalmente valido per la nazione indicata.",
            ],
            'consigneeCity' => [
                'dato_obbligatorio' => false,
                'mandatory_if' => 'brtServiceCode non è B15',
                'rif_brt_vab' => 'VABLOD',
                'max_length' => '35',
                'precision' => '',
                'scale' => '',
                'description' => "Località di destinazione. [rif. BRT VABLOD] [max length =35]\nDato obbligatorio se brtServiceCode non è B15.",
            ],
            'consigneeProvinceAbbreviation' => [
                'dato_obbligatorio' => false,
                'mandatory_if' => '',
                'rif_brt_vab' => 'VABPRD',
                'max_length' => '2',
                'precision' => '',
                'scale' => '',
                'description' => "Sigla della provincia di destinazione. [rif. BRT VABPRD] [max length =2]\nViene controllato che sia formalmente valido rispetto all'elenco sigle delle provincie italiane. Dato facoltativo.",
            ],
            'consigneeCountryAbbreviationISOAlpha2' => [
                'dato_obbligatorio' => false,
                'mandatory_if' => 'brtServiceCode non è B15',
                'rif_brt_vab' => 'VABNZD',
                'max_length' => '2',
                'precision' => '',
                'scale' => '',
                'description' => "Sigla della nazione di destinazione. [rif. BRT VABNZD] [max length =2]\nDato obbligatorio se brtServiceCode non è B15. Deve essere indicata l'abbreviazione ISO 3166-1 alpha-2.",
            ],
            'consigneeClosingShift1_DayOfTheWeek' => [
                'dato_obbligatorio' => false,
                'mandatory_if' => '',
                'rif_brt_vab' => 'VABGC1',
                'max_length' => '3',
                'precision' => '',
                'scale' => '',
                'description' => "Giorno di chiusura 1. [rif. parte BRT VABGC1] [max length =3]\nDato facoltativo. Può valere: 'MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', 'SUN'. Se non passato, ma passato il dato consigneeClosingShift1_PeriodOfTheDay, è come indicare 'tutta la settimana'.",
            ],
            'consigneeClosingShift1_PeriodOfTheDay' => [
                'dato_obbligatorio' => false,
                'mandatory_if' => '',
                'rif_brt_vab' => 'VABGC1',
                'max_length' => '2',
                'precision' => '',
                'scale' => '',
                'description' => "Periodo di chiusura nel giorno 1. [rif. parte BRT VABGC1]  [max length =2]\nDato facoltativo. Può valere: 'AM', 'PM'. Se non passato, ma passato il dato consigneeClosingShift1_DayOfTheWeek, è come indicare 'tutto il giorno'.",
            ],
            'consigneeClosingShift2_DayOfTheWeek' => [
                'dato_obbligatorio' => false,
                'mandatory_if' => '',
                'rif_brt_vab' => 'VABGC2',
                'max_length' => '3',
                'precision' => '',
                'scale' => '',
                'description' => "Giorno di chiusura 2. [rif. parte BRT VABGC2]  [max length =3]\nDato facoltativo. Può valere: 'MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', 'SUN'. Se non passato, ma passato il dato consigneeClosingShift2_PeriodOfTheDay, è come indicare 'tutta la settimana'.",
            ],
            'consigneeClosingShift2_PeriodOfTheDay' => [
                'dato_obbligatorio' => false,
                'mandatory_if' => '',
                'rif_brt_vab' => 'VABGC2',
                'max_length' => '2',
                'precision' => '',
                'scale' => '',
                'description' => "Periodo di chiusura nel giorno 2. [rif. parte BRT VABGC2]  [max length =2]\nDato facoltativo. Può valere: 'AM', 'PM'. Se non passato, ma passato il dato consigneeClosingShift2_DayOfTheWeek, è come indicare 'tutto il giorno'.",
            ],
            'consigneeContactName' => [
                'dato_obbligatorio' => false,
                'mandatory_if' => '',
                'rif_brt_vab' => 'VATNOT VATTRC=A',
                'max_length' => '35',
                'precision' => '',
                'scale' => '',
                'description' => "Referente consegna. [rif. BRT VATNOT + VATTRC=A]  [max length =35]\nDato facoltativo. Dato Case sensitive.",
            ],
            'consigneeTelephone' => [
                'dato_obbligatorio' => false,
                'mandatory_if' => '',
                'rif_brt_vab' => 'VATNOT VATTRC=B',
                'max_length' => '16',
                'precision' => '',
                'scale' => '',
                'description' => "Telefono referente consegna. [rif. BRT VATNOT + VATTRC=B]  [max length =16]\nDato facoltativo.",
            ],
            'consigneeEMail' => [
                'dato_obbligatorio' => false,
                'mandatory_if' => '',
                'rif_brt_vab' => 'VATNOT VATTRC=I e J',
                'max_length' => '70',
                'precision' => '',
                'scale' => '',
                'description' => "EMail referente consegna. [rif. BRT VATNOT + VATTRC=I e J]  [max length =70]\nDato facoltativo. Se valorizzato a '1' il dato isAlertRequired, verrà mandato l'alert al destinatario via email a questo indirizzo (se previsto dal contratto con BRT). Se si vogliono indicare più indirizzi, questi vanno separati dal carattere barra verticale o pipe (|).",
            ],
            'consigneeMobilePhoneNumber' => [
                'dato_obbligatorio' => false,
                'mandatory_if' => '',
                'rif_brt_vab' => 'VATNOT VATTRC=S',
                'max_length' => '16',
                'precision' => '',
                'scale' => '',
                'description' => "Mobile referente consegna. [rif. BRT VATNOT + VATTRC=S]  [max length =16]\nDato facoltativo. Se valorizzato a '1' il dato isAlertRequired, verrà mandato l'alert al destinatario via SMS a questo numero (se previsto dal contratto con BRT).",
            ],
            'isAlertRequired' => [
                'dato_obbligatorio' => false,
                'mandatory_if' => '',
                'rif_brt_vab' => '',
                'max_length' => '',
                'precision' => '',
                'scale' => '',
                'description' => "Richiesta Alert. Può valere '0' o '1'.",
            ],
            'consigneeVATNumber' => [
                'dato_obbligatorio' => false,
                'mandatory_if' => '',
                'rif_brt_vab' => 'VATNOT VATTRC=R',
                'max_length' => '16',
                'precision' => '',
                'scale' => '',
                'description' => "Numero partita IVA. [rif. parte BRT VATNOT + VATTRC=R]  [max length =16]\nDato facoltativo.",
            ],
            'consigneeVATNumberCountryISOAlpha2' => [
                'dato_obbligatorio' => false,
                'mandatory_if' => '',
                'rif_brt_vab' => 'VATNOT VATTRC=A',
                'max_length' => '2',
                'precision' => '',
                'scale' => '',
                'description' => "Sigla nazione partita IVA.  [rif. parte BRT VATNOT + VATTRC=A] [max length=2]\nDato facoltativo. Se indicato, deve essere l'abbreviazione ISO 3166-1 alpha-2.",
            ],
            'consigneeItalianFiscalCode' => [
                'dato_obbligatorio' => false,
                'mandatory_if' => '',
                'rif_brt_vab' => 'VATNOT VATTRC=Q',
                'max_length' => '16',
                'precision' => '',
                'scale' => '',
                'description' => "Codice fiscale italiano. [rif. BRT VATNOT + VATTRC=Q] [max length=16]\nDato facoltativo. Dato Case sensitive.",
            ],
            'pricingConditionCode' => [
                'dato_obbligatorio' => false,
                'mandatory_if' => '',
                'rif_brt_vab' => 'VABCTR',
                'max_length' => '',
                'precision' => '3',
                'scale' => '0',
                'description' => "Codice tariffa. [rif. BRT VABCTR]  [precision  =3 scale=0]\nViene comunicato da BRT. In caso che il cliente abbia più tariffe, saranno comunicati più valori. In ogni singola richiesta può essere indicato un solo valore. Viene controllata l'esistenza del dato e l'appartenenza al cliente.",
            ],
            'serviceType' => [
                'dato_obbligatorio' => false,
                'mandatory_if' => '',
                'rif_brt_vab' => 'VABTSP',
                'max_length' => '1',
                'precision' => '',
                'scale' => '',
                'description' => "Tipo servizio. [rif. BRT VABTSP] [max length=1]\nIl suo significato viene spiegato da BRT. Se indicata stringa vuota viene preso il default BRT. Può valere: Default = servizio standard, 'E' = servizio priority, 'H' = servizio 10:30.",
            ],
            'insuranceAmount' => [
                'dato_obbligatorio' => false,
                'mandatory_if' => '',
                'rif_brt_vab' => 'VABIAS',
                'max_length' => '',
                'precision' => '7',
                'scale' => '2',
                'description' => "Importo assicurazione sulla spedizione. [rif. BRT VABIAS] [precision =7 scale=2]\nDato facoltativo.",
            ],
            'insuranceAmountCurrency' => [
                'dato_obbligatorio' => false,
                'mandatory_if' => 'insuranceAmount valorizzato',
                'rif_brt_vab' => 'VABVAS',
                'max_length' => '3',
                'precision' => '',
                'scale' => '',
                'description' => "Divisa dell'importo assicurazione sulla spedizione. [rif. BRT VABVAS] [max length=3]\nDato facoltativo. Se omesso ma valorizzato insuranceAmount, viene impostato 'EUR'.",
            ],
            'senderParcelType' => [
                'dato_obbligatorio' => false,
                'mandatory_if' => '',
                'rif_brt_vab' => 'VABNAS',
                'max_length' => '15',
                'precision' => '',
                'scale' => '',
                'description' => "Natura merce. [rif. BRT VABNAS] [max length=15]\nDato facoltativo. Dato Case sensitive.",
            ],
            'numberOfParcels' => [
                'dato_obbligatorio' => true,
                'mandatory_if' => '',
                'rif_brt_vab' => 'VABNCL',
                'max_length' => '',
                'precision' => '2',
                'scale' => '0',
                'description' => "Numero di pacchi. [rif. BRT VABNCL] [precision =2 scale=0]\nDato obbligatorio. Il numero massimo di colli richiedibili è 30.",
            ],
            'weightKG' => [
                'dato_obbligatorio' => true,
                'mandatory_if' => '',
                'rif_brt_vab' => 'VABPKB',
                'max_length' => '',
                'precision' => '5',
                'scale' => '1',
                'description' => "Peso totale della spedizione in chilogrammi. [rif. BRT VABPKB]  [precision =5 scale=1]\nDato obbligatorio.",
            ],
            'volumeM3' => [
                'dato_obbligatorio' => false,
                'mandatory_if' => '',
                'rif_brt_vab' => 'VABVLB',
                'max_length' => '',
                'precision' => '5',
                'scale' => '3',
                'description' => "Volume totale della spedizione in metri cubi. [rif. BRT VABVLB] [precision =5 scale=3]\nDato facoltativo.",
            ],
            'quantityToBeInvoiced' => [
                'dato_obbligatorio' => false,
                'mandatory_if' => '',
                'rif_brt_vab' => 'VABQFT',
                'max_length' => '',
                'precision' => '7',
                'scale' => '3',
                'description' => "Quantità da fatturare. [rif. BRT VABQFT] [precision =7 scale=3]\nDato facoltativo.",
            ],
            'cashOnDelivery' => [
                'dato_obbligatorio' => false,
                'mandatory_if' => "isCODMandatory = '1'",
                'rif_brt_vab' => 'VABCAS',
                'max_length' => '',
                'precision' => '7',
                'scale' => '2',
                'description' => "Contrassegno. [rif. BRT VABCAS] [precision =7 scale=2]\nDato facoltativo. Se valorizzato a '1' il dato isCODMandatory, questo dato deve essere valorizzato.",
            ],
            'isCODMandatory' => [
                'dato_obbligatorio' => false,
                'mandatory_if' => '',
                'rif_brt_vab' => '',
                'max_length' => '',
                'precision' => '',
                'scale' => '',
                'description' => "Contrassegno obbligatorio. Può valere '0' o '1'.",
            ],
            'codPaymentType' => [
                'dato_obbligatorio' => false,
                'mandatory_if' => "isCODMandatory = '1'",
                'rif_brt_vab' => 'VABTIC',
                'max_length' => '2',
                'precision' => '',
                'scale' => '',
                'description' => "Tipo pagamento contrassegno. [rif. BRT VABTIC] [max length=2]\nDato facoltativo. Se valorizzato a '1' il dato isCODMandatory, questo dato può essere valorizzato. Se valorizzato, viene controllata l'esistenza del dato.",
            ],
            'codCurrency' => [
                'dato_obbligatorio' => false,
                'mandatory_if' => "isCODMandatory = '1'",
                'rif_brt_vab' => 'VABVCA',
                'max_length' => '3',
                'precision' => '',
                'scale' => '',
                'description' => "Divisa contrassegno. [rif. BRT VABVCA] [max length=3]\nDato facoltativo. Se valorizzato a '1' il dato isCODMandatory, questo dato può essere valorizzato. Se valorizzato, viene controllata l'esistenza del dato.",
            ],
            'numericSenderReference' => [
                'dato_obbligatorio' => true,
                'mandatory_if' => '',
                'rif_brt_vab' => 'VABRMN',
                'max_length' => '',
                'precision' => '15',
                'scale' => '0',
                'description' => "Riferimento mittente numerico. [rif. BRT VABRMN] [precision=15 scale=0]\nDato obbligatorio.",
            ],
            'alphanumericSenderReference' => [
                'dato_obbligatorio' => false,
                'mandatory_if' => '',
                'rif_brt_vab' => 'VABRMA',
                'max_length' => '15',
                'precision' => '',
                'scale' => '',
                'description' => "Riferimento mittente alfanumerico. [rif. BRT VABRMA] [max length=15]\nDato facoltativo. Dato Case sensitive.",
            ],
            'notes' => [
                'dato_obbligatorio' => false,
                'mandatory_if' => '',
                'rif_brt_vab' => 'VABNOT VABNT2',
                'max_length' => '70',
                'precision' => '',
                'scale' => '',
                'description' => "Note. [rif. BRT VABNOT VABNT2] [max length=70]\nDato facoltativo. Dato Case sensitive.",
            ],
            'parcelsHandlingCode' => [
                'dato_obbligatorio' => false,
                'mandatory_if' => '',
                'rif_brt_vab' => 'VABCTM',
                'max_length' => '2',
                'precision' => '',
                'scale' => '',
                'description' => "Codice trattamento merce. [rif. BRT VABCTM] [max length=2]\nDato facoltativo. Viene comunicato da BRT, nel caso serva un valore specifico. In caso contrario lasciare vuoto.",
            ],
            'deliveryDateRequired' => [
                'dato_obbligatorio' => false,
                'mandatory_if' => '',
                'rif_brt_vab' => 'VABDCR',
                'max_length' => '10',
                'precision' => '',
                'scale' => '',
                'description' => "Data consegna richiesta. [rif. BRT VABDCR] [max length=10]\nDato facoltativo. Data in formato date *ISO [yyyy-MM-dd].",
            ],
            'deliveryType' => [
                'dato_obbligatorio' => false,
                'mandatory_if' => '',
                'rif_brt_vab' => 'VABTCR',
                'max_length' => '1',
                'precision' => '',
                'scale' => '',
                'description' => "Tipo di consegna rispetto alla data di consegna richiesta. [rif. BRT VABTCR] [max length=1]\nDato facoltativo.",
            ],
            'declaredParcelValue' => [
                'dato_obbligatorio' => false,
                'mandatory_if' => '',
                'rif_brt_vab' => 'VABVMD',
                'max_length' => '',
                'precision' => '7',
                'scale' => '2',
                'description' => "Valore merce dichiarato. [rif. BRT VABVMD]  [precision=7 scale=2]\nDato facoltativo.",
            ],
            'declaredParcelValueCurrency' => [
                'dato_obbligatorio' => false,
                'mandatory_if' => 'declaredParcelValue valorizzato',
                'rif_brt_vab' => 'VABVAD',
                'max_length' => '3',
                'precision' => '',
                'scale' => '',
                'description' => "Divisa valore merce dichiarato. [rif. BRT VABVAD]  [max length=3]\nDato facoltativo. Se omesso ma valorizzato declaredParcelValue, viene impostato 'EUR'.",
            ],
            'particularitiesDeliveryManagementCode' => [
                'dato_obbligatorio' => false,
                'mandatory_if' => '',
                'rif_brt_vab' => 'VABGMA',
                'max_length' => '2',
                'precision' => '',
                'scale' => '',
                'description' => "Gestione particolarietà di consegna. [rif. BRT VABGMA]  [max length=2]\nDato facoltativo. Sono più valori, che vengono comunicati da BRT. Viene controllata l'esistenza del dato.",
            ],
            'particularitiesHoldOnStockManagementCode' => [
                'dato_obbligatorio' => false,
                'mandatory_if' => '',
                'rif_brt_vab' => 'VABGCA',
                'max_length' => '2',
                'precision' => '',
                'scale' => '',
                'description' => "Gestione particolarietà di giacenza. [rif. BRT VABGCA] [max length=2]\nDato facoltativo. Sono più valori, che vengono comunicati da BRT. Viene controllata l'esistenza del dato.",
            ],
            'variousParticularitiesManagementCode' => [
                'dato_obbligatorio' => false,
                'mandatory_if' => '',
                'rif_brt_vab' => 'VABGVA',
                'max_length' => '2',
                'precision' => '',
                'scale' => '',
                'description' => "Gestione particolarietà varie. [rif. BRT VABGVA] [max length=2]\nDato facoltativo. Sono più valori, che vengono comunicati da BRT. Viene controllata l'esistenza del dato.",
            ],
            'particularDelivery1' => [
                'dato_obbligatorio' => false,
                'mandatory_if' => '',
                'rif_brt_vab' => 'VABTC1',
                'max_length' => '1',
                'precision' => '',
                'scale' => '',
                'description' => "Particolarità di consegna 1. [rif. BRT VABTC1]  [max length=1]\nDato facoltativo. Sono più valori, che vengono comunicati da BRT. Viene controllata l'esistenza del dato.",
            ],
            'particularDelivery2' => [
                'dato_obbligatorio' => false,
                'mandatory_if' => '',
                'rif_brt_vab' => 'VABTC2',
                'max_length' => '1',
                'precision' => '',
                'scale' => '',
                'description' => "Particolarità di consegna 2. [rif. BRT VABTC2] [max length=1]\nDato facoltativo. Sono più valori, che vengono comunicati da BRT. Viene controllata l'esistenza del dato.",
            ],
            'palletType1' => [
                'dato_obbligatorio' => false,
                'mandatory_if' => '',
                'rif_brt_vab' => 'VABANT',
                'max_length' => '4',
                'precision' => '',
                'scale' => '',
                'description' => "Tipo pallet 1. [rif. parte BRT VABANT] [max length=4]\nDato facoltativo. Può valere 'EPAL'.",
            ],
            'palletType1Number' => [
                'dato_obbligatorio' => false,
                'mandatory_if' => 'palletType1 valorizzato',
                'rif_brt_vab' => 'VABANT',
                'max_length' => '',
                'precision' => '2',
                'scale' => '0',
                'description' => "Numero di pallet del tipo 1. [rif. parte BRT VABANT] [precision=2 scale=0]\nDato facoltativo. Se valorizzato palletType1, diventa obbligatorio.",
            ],
            'palletType2' => [
                'dato_obbligatorio' => false,
                'mandatory_if' => '',
                'rif_brt_vab' => 'VABANT',
                'max_length' => '4',
                'precision' => '',
                'scale' => '',
                'description' => "Tipo pallet 2. [rif. parte BRT VABANT] [max length=4]\nDato facoltativo. Può valere 'EPAL'.",
            ],
            'palletType2Number' => [
                'dato_obbligatorio' => false,
                'mandatory_if' => 'palletType2 valorizzato',
                'rif_brt_vab' => 'VABANT',
                'max_length' => '',
                'precision' => '2',
                'scale' => '0',
                'description' => "Numero di pallet del tipo 2. [rif. parte BRT VABANT] [precision=2 scale=0]\nDato facoltativo. Se valorizzato palletType2, diventa obbligatorio.",
            ],
            'originalSenderCompanyName' => [
                'dato_obbligatorio' => false,
                'mandatory_if' => '',
                'rif_brt_vab' => 'VABRMO',
                'max_length' => '25',
                'precision' => '',
                'scale' => '',
                'description' => "Ragione sociale mittente. [rif. BRT VABRMO] [max length=25]\nDato facoltativo. Dato Case sensitive.",
            ],
            'originalSenderZIPCode' => [
                'dato_obbligatorio' => false,
                'mandatory_if' => '',
                'rif_brt_vab' => 'VABCMO',
                'max_length' => '9',
                'precision' => '',
                'scale' => '',
                'description' => "CAP nel formato della nazione del mittente. [rif. BRT VABCMO] [max length=9]\nDato facoltativo. Se indicato, viene controllato che sia formalmente valido per la nazione indicata.",
            ],
            'originalSenderCountryAbbreviationISOAlpha2' => [
                'dato_obbligatorio' => false,
                'mandatory_if' => '',
                'rif_brt_vab' => 'VABNMO',
                'max_length' => '2',
                'precision' => '',
                'scale' => '',
                'description' => "Sigla della nazione del mittente. [rif. BRT VABNMO] [max length=2]\nDato facoltativo. Deve essere indicata l'abbreviazione ISO 3166-1 alpha-2.",
            ],
            'cmrCode' => [
                'dato_obbligatorio' => false,
                'mandatory_if' => 'si passa dal accorpamento bolle',
                'rif_brt_vab' => 'VABCMR',
                'max_length' => '35',
                'precision' => '',
                'scale' => '',
                'description' => "Codice CMR. [rif. BRT VABCMR] [max length=35]\nCampo obbligatorio se si passa dal accorpamento bolle, altrimenti può essere lasciato vuoto. Dato Case sensitive.",
            ],
            'neighborNameMandatoryAuthorization' => [
                'dato_obbligatorio' => false,
                'mandatory_if' => 'autorizzazione BRT',
                'rif_brt_vab' => 'VATNOT VATTRC=V e W',
                'max_length' => '70',
                'precision' => '',
                'scale' => '',
                'description' => "Nome vicino a cui consegnare in assenza del destinatario (obbligatoria autorizzazione). [rif. BRT VATNOT + VATTRC=V e W] [max length=70]\nDato facoltativo. Dato Case sensitive. Se indicato, viene utilizzato solo previa autorizzazione BRT.",
            ],
            'pinCodeMandatoryAuthorization' => [
                'dato_obbligatorio' => false,
                'mandatory_if' => 'autorizzazione BRT',
                'rif_brt_vab' => 'VATNOT VATTRC=Y',
                'max_length' => '15',
                'precision' => '',
                'scale' => '',
                'description' => "PIN code (obbligatoria autorizzazione). [rif. BRT VATNOT + VATTRC=Y] [max length=15]\nDato facoltativo. Se indicato, viene utilizzato solo previa autorizzazione BRT.",
            ],
            'packingListPDFName' => [
                'dato_obbligatorio' => false,
                'mandatory_if' => '',
                'rif_brt_vab' => 'VATNOT VATTRC=P',
                'max_length' => '33',
                'precision' => '',
                'scale' => '',
                'description' => "Nome del packing list PDF. [rif. parte BRT VATNOT + VATTRC=P] [max length=33]\nDato facoltativo.",
            ],
            'packingListPDFFlagPrint' => [
                'dato_obbligatorio' => false,
                'mandatory_if' => '',
                'rif_brt_vab' => 'VATNOT VATTRC=P',
                'max_length' => '1',
                'precision' => '',
                'scale' => '',
                'description' => "Flag 1 stampa del packing list PDF. [rif. parte BRT VATNOT + VATTRC=P] [max length=1]\nDato facoltativo. Valore comunicato da BRT.",
            ],
            'packingListPDFFlagEmail' => [
                'dato_obbligatorio' => false,
                'mandatory_if' => '',
                'rif_brt_vab' => 'VATNOT VATTRC=P',
                'max_length' => '1',
                'precision' => '',
                'scale' => '',
                'description' => "Flag 1 stampa del packing list PDF. [rif. parte BRT VATNOT + VATTRC=P] [max length=1]\nDato facoltativo. Valore comunicato da BRT.",
            ],
            'pudoId' => [
                'dato_obbligatorio' => false,
                'mandatory_if' => '',
                'rif_brt_vab' => '',
                'max_length' => '20',
                'precision' => '',
                'scale' => '',
                'description' => "Identificativo del PUDO BRTfermopoint. [max length=20]\nDato facoltativo. Se valorizzato pudoId, nel caso in cui l'indirizzo di consegna sia diverso dall'indirizzo del PUDO presente nell'anagrafica di BRT, la spedizione viene creata correttamente al indirizzo del PUDO, ma l'esito del servizio restituisce un warning(code 5). Nel caso una spedizione sia consegnata a PUDO deve essere valorizzato almeno uno tra consegneeEMail e consegneeMobilePhoneNumber.",
            ],
            'brtServiceCode' => [
                'dato_obbligatorio' => false,
                'mandatory_if' => '',
                'rif_brt_vab' => '',
                'max_length' => '3',
                'precision' => '',
                'scale' => '',
                'description' => "BRT Service Code. [max length=3]\nDato facoltativo. Default = servizio standard. 'B11' = servizio Direct to Shop. Viene controllato che sia presente il pudoId, che sia formalmente valido e che le caratteristiche della spedizione siano compatibili con il BRT Service Code. ‘B13’ = servizio Shop to Shop. Viene controllato che sia presente il pudoId, che sia formalmente valido e che le caratteristiche della spedizione siano compatibili con il BRT Service Code. ‘B14’ = servizio Shop to Home. Viene controllato che la spedizione non sia diretta a un PUDO BRTfermopoint e che le caratteristiche della spedizione siano compatibili con il BRT Service Code. ‘B15’ = servizio Return from Shop. Viene controllato che sia compilato correttamente il dato returnDepot. Non occorrono i dati del destinatario, se presenti verranno sostituiti con i dati del Deposito di reso. 'B20' = Servizio FRESH per spedizioni a temperatura controllata e garantita (0 °C -  4°C).",
            ],
            'returnDepot' => [
                'dato_obbligatorio' => false,
                'mandatory_if' => 'tipo servizio',
                'rif_brt_vab' => '',
                'max_length' => '',
                'precision' => '10',
                'scale' => '0',
                'description' => "Deposito di reso [precision=10 scale=0]\nDato obbligatorio a seconda del tipo servizio. Viene comunicato da BRT. In caso che il cliente abbia associati più depositi di reso, saranno comunicati più valori. In ogni singola richiesta può essere indicato un solo valore.",
            ],
            'expiryDate' => [
                'dato_obbligatorio' => false,
                'mandatory_if' => 'servizio Fresh',
                'rif_brt_vab' => '',
                'max_length' => '10',
                'precision' => '',
                'scale' => '',
                'description' => "Data scadenza. [max length=10]\nDato obbligatorio per il servizio Fresh. Data in formato date *ISO [yyyy-MM-dd].",
            ],
            'holdForPickup' => [
                'dato_obbligatorio' => false,
                'mandatory_if' => '',
                'rif_brt_vab' => '',
                'max_length' => '1',
                'precision' => '',
                'scale' => '',
                'description' => "Fermo deposito [max length=1]\nDato facoltativo. Può valere '0' o '1'.",
            ],
            'genericReference' => [
                'dato_obbligatorio' => false,
                'mandatory_if' => '',
                'rif_brt_vab' => '',
                'max_length' => '35',
                'precision' => '',
                'scale' => '',
                'description' => "Riferimento generico [max length=35]\nDato facoltativo. Se impostato, può essere aggiunto come informazione nei file restituiti al cliente dalle procerdure BRT. NON è un campo utilizzabile nelle ricerche track & trace.",
            ],
            'isLabelRequired' => [
                'dato_obbligatorio' => true,
                'mandatory_if' => '',
                'rif_brt_vab' => '',
                'max_length' => '',
                'precision' => '',
                'scale' => '',
                'description' => "Dato obbligatorio. Se indicato '1' viene richiesta l'etichetta da applicare al pacco.",
            ],
            'labelParameters' => [
                'dato_obbligatorio' => true,
                'mandatory_if' => "isLabelRequired = '1'",
                'rif_brt_vab' => '',
                'max_length' => '',
                'precision' => '',
                'scale' => '',
                'description' => "Dato obbligatorio se indicato '1' in isLabelRequired. Nel caso non sia indicato '1' in isLabelRequired il parametro non deve essere valorizzato (può essere omesso).",
            ],
            'outputType' => [
                'dato_obbligatorio' => true,
                'mandatory_if' => "isLabelRequired = '1'",
                'rif_brt_vab' => '',
                'max_length' => '',
                'precision' => '',
                'scale' => '',
                'description' => "Dato obbligatorio se indicato isLabelRequired = '1'. Deve valere: 'PDF' = Formato etichetta in PDF, 'ZPL' = Formato ASCII dell'etichetta con codifica standard ZPL (Zebra Programming Language).",
            ],
            'offsetX' => [
                'dato_obbligatorio' => true,
                'mandatory_if' => "isLabelRequired = '1'",
                'rif_brt_vab' => '',
                'max_length' => '',
                'precision' => '',
                'scale' => '',
                'description' => "Dato obbligatorio se indicato isLabelRequired = '1'. Nel caso il parametro venisse omesso oppure venisse passato un dato alfanumerico, viene forzato il valore 0 (zero). Distanza orizzontale dal vertice in alto a sinistra.",
            ],
            'offsetY' => [
                'dato_obbligatorio' => true,
                'mandatory_if' => "isLabelRequired = '1'",
                'rif_brt_vab' => '',
                'max_length' => '',
                'precision' => '',
                'scale' => '',
                'description' => "Dato obbligatorio se indicato isLabelRequired = '1'. Nel caso il parametro venisse omesso oppure venisse passato un dato alfanumerico, viene forzato il valore 0 (zero). Distanza verticale dal vertice in alto a sinistra.",
            ],
            'isBorderRequired' => [
                'dato_obbligatorio' => true,
                'mandatory_if' => "isLabelRequired = '1'",
                'rif_brt_vab' => '',
                'max_length' => '',
                'precision' => '',
                'scale' => '',
                'description' => "Dato obbligatorio se indicato isLabelRequired = '1'. Nel caso il parametro venisse omesso oppure venisse passato un dato diverso da '0' e '1', viene forzato il valore '0' (zero). Se vale '1' viene creato un bordo all'etichetta.",
            ],
            'isLogoRequired' => [
                'dato_obbligatorio' => true,
                'mandatory_if' => "isLabelRequired = '1'",
                'rif_brt_vab' => '',
                'max_length' => '',
                'precision' => '',
                'scale' => '',
                'description' => "Dato obbligatorio se indicato isLabelRequired = '1'. Nel caso il parametro venisse omesso oppure venisse passato un dato diverso da '0' e '1', viene forzato il valore '0' (zero). Se vale '1' viene creato il logo BRT sull'etichetta.",
            ],
            'isBarcodeControlRowRequired' => [
                'dato_obbligatorio' => true,
                'mandatory_if' => "isLabelRequired = '1'",
                'rif_brt_vab' => '',
                'max_length' => '',
                'precision' => '',
                'scale' => '',
                'description' => "Dato obbligatorio se indicato isLabelRequired = '1'. Nel caso il parametro venisse omesso oppure venisse passato un dato diverso da '0' e '1', viene forzato il valore '0' (zero). Se vale '1' viene creata una riga di controllo sopra al barcode.",
            ],
            'labelFormat' => [
                'dato_obbligatorio' => false,
                'mandatory_if' => '',
                'rif_brt_vab' => '',
                'max_length' => '',
                'precision' => '',
                'scale' => '',
                'description' => "Dato facoltativo. Se valorizzato, indica il formato dell'etichetta che verrà restituita. I valori possibili sono: Se non passato oppure impostata stringa vuota, sarà restituita l'etichetta BRT - Formato 95 mm * 65 mm. 'DP5': etichetta DPD solo per clienti abilitati al Direct Infeed - Formato 100 mm * 150 mm, l'OutputType in questo caso è solo ZPL. 'DPH': etichetta \"ibrida\" DPD/BRT solo per clienti abilitati - Formato 100 mm * 150 mm, l'OutputType in questo caso è solo ZPL.",
            ],
            'actualSenderName' => [
                'dato_obbligatorio' => true,
                'mandatory_if' => '',
                'rif_brt_vab' => '',
                'max_length' => '70',
                'precision' => '',
                'scale' => '',
                'description' => "Nome del mittente reale.  [Maxlegth=70]\nDato obbligatorio.",
            ],
            'actualSenderCity' => [
                'dato_obbligatorio' => false,
                'mandatory_if' => '',
                'rif_brt_vab' => '',
                'max_length' => '35',
                'precision' => '',
                'scale' => '',
                'description' => "Località del mittente reale.  [Maxlegth=35]\nDato Facoltativo.",
            ],
            'actualSenderAddress' => [
                'dato_obbligatorio' => false,
                'mandatory_if' => '',
                'rif_brt_vab' => '',
                'max_length' => '35',
                'precision' => '',
                'scale' => '',
                'description' => "Indirizzo del mittente reale.  [Maxlegth=35]\nDato Facoltativo.",
            ],
            'actualSenderZIPCode' => [
                'dato_obbligatorio' => false,
                'mandatory_if' => '',
                'rif_brt_vab' => '',
                'max_length' => '9',
                'precision' => '',
                'scale' => '',
                'description' => "CAP nel formato della nazione del mittente reale.  [Maxlegth=9]\nDato Facoltativo. Viene controllato che sia formalmente valido per la nazione indicata.",
            ],
            'actualSenderProvince' => [
                'dato_obbligatorio' => false,
                'mandatory_if' => '',
                'rif_brt_vab' => '',
                'max_length' => '2',
                'precision' => '',
                'scale' => '',
                'description' => "Sigla della provincia del mittente reale.  [Maxlegth=2]\nDato Facoltativo. Viene controllato che sia formalmente valido rispetto all'elenco sigle delle provincie italiane.",
            ],
            'actualSenderCountry' => [
                'dato_obbligatorio' => false,
                'mandatory_if' => '',
                'rif_brt_vab' => '',
                'max_length' => '3',
                'precision' => '',
                'scale' => '',
                'description' => "Sigla della nazione del mittente reale.  [Maxlegth=3]\nDato Facoltativo. Deve essere indicata l'abbreviazione ISO 3166-1 alpha-2.",
            ],
            'actualSenderEmail' => [
                'dato_obbligatorio' => true,
                'mandatory_if' => 'almeno uno tra actualSenderEmail e actualSenderMobilePhoneNumber',
                'rif_brt_vab' => '',
                'max_length' => '70',
                'precision' => '',
                'scale' => '',
                'description' => "Email del mittente reale.  [Maxlegth=70]\nDato obbligatorio. deve essere valorizzato almeno uno dei due campi tra actualSenderEmail e actualSenderMobilePhoneNumber.",
            ],
            'actualSenderMobilePhoneNumber' => [
                'dato_obbligatorio' => true,
                'mandatory_if' => 'almeno uno tra actualSenderEmail e actualSenderMobilePhoneNumber',
                'rif_brt_vab' => '',
                'max_length' => '16',
                'precision' => '',
                'scale' => '',
                'description' => "Mobile del mittente reale.  [Maxlegth=16]\nDato obbligatorio. deve essere valorizzato almeno uno dei due campi tra actualSenderEmail e actualSenderMobilePhoneNumber.",
            ],
            'actualSenderPudoId' => [
                'dato_obbligatorio' => false,
                'mandatory_if' => '',
                'rif_brt_vab' => '',
                'max_length' => '20',
                'precision' => '',
                'scale' => '',
                'description' => "Id pudo del mittente reale.  [Maxlegth=20]\nDato facoltativo. Se valorizzato actualSenderPudoId, nel caso in cui l'indirizzo di consegna sia diverso dall'indirizzo del PUDO presente nell'anagrafica di BRT, la spedizione viene creata correttamente al indirizzo del PUDO, ma l'esito del servizio restituisce un warning (5).",
            ],
            'returnShipmentConsigneeName' => [
                'dato_obbligatorio' => true,
                'mandatory_if' => '',
                'rif_brt_vab' => '',
                'max_length' => '70',
                'precision' => '',
                'scale' => '',
                'description' => "Nome del destinatario del reso.  [Maxlegth=70]\nDato obbligatorio.",
            ],
            'returnShipmentConsigneeCity' => [
                'dato_obbligatorio' => true,
                'mandatory_if' => '',
                'rif_brt_vab' => '',
                'max_length' => '35',
                'precision' => '',
                'scale' => '',
                'description' => "Località del destinatario del reso.  [Maxlegth=35]\nDato obbligatorio.",
            ],
            'returnShipmentConsigneeAddress' => [
                'dato_obbligatorio' => true,
                'mandatory_if' => '',
                'rif_brt_vab' => '',
                'max_length' => '35',
                'precision' => '',
                'scale' => '',
                'description' => "Indirizzo del destinatario del reso.  [Maxlegth=35]\nDato obbligatorio.",
            ],
            'returnShipmentConsigneeZIPCode' => [
                'dato_obbligatorio' => true,
                'mandatory_if' => '',
                'rif_brt_vab' => '',
                'max_length' => '9',
                'precision' => '',
                'scale' => '',
                'description' => "CAP nel formato della nazione del destinatario del reso.  [Maxlegth=9]\nDato obbligatorio. Viene controllato che sia formalmente valido per la nazione indicata.",
            ],
            'returnShipmentConsigneeProvince' => [
                'dato_obbligatorio' => false,
                'mandatory_if' => '',
                'rif_brt_vab' => '',
                'max_length' => '2',
                'precision' => '',
                'scale' => '',
                'description' => "Sigla della provincia del destinatario del reso.  [Maxlegth=2]\nDato Opzionale. Viene controllato che sia formalmente valido rispetto all'elenco sigle delle provincie italiane.",
            ],
            'returnShipmentConsigneeCountry' => [
                'dato_obbligatorio' => true,
                'mandatory_if' => '',
                'rif_brt_vab' => '',
                'max_length' => '3',
                'precision' => '',
                'scale' => '',
                'description' => "Sigla della nazione del destinatario del reso.  [Maxlegth=3]\nDato obbligatorio. Deve essere indicata l'abbreviazione ISO 3166-1 alpha-2.",
            ],
            'returnShipmentConsigneeEmail' => [
                'dato_obbligatorio' => true,
                'mandatory_if' => 'almeno uno tra returnShipmentConsigneeEmail e returnShipmentConsigneeMobilePhoneNumber',
                'rif_brt_vab' => '',
                'max_length' => '70',
                'precision' => '',
                'scale' => '',
                'description' => "Email del destinatario del reso.  [Maxlegth=70]\nDato obbligatorio. deve essere valorizzato almeno uno dei due campi tra returnShipmentConsigneeEmail e returnShipmentConsigneeMobilePhoneNumber.",
            ],
            'returnShipmentConsigneeMobilePhoneNumber' => [
                'dato_obbligatorio' => true,
                'mandatory_if' => 'almeno uno tra returnShipmentConsigneeEmail e returnShipmentConsigneeMobilePhoneNumber',
                'rif_brt_vab' => '',
                'max_length' => '16',
                'precision' => '',
                'scale' => '',
                'description' => "Mobile del destinatario del reso.  [Maxlegth=16]\nDato obbligatorio. deve essere valorizzato almeno uno dei due campi tra returnShipmentConsigneeEmail e returnShipmentConsigneeMobilePhoneNumber.",
            ],
            'returnShipmentConsigneePudoId' => [
                'dato_obbligatorio' => false,
                'mandatory_if' => '',
                'rif_brt_vab' => '',
                'max_length' => '20',
                'precision' => '',
                'scale' => '',
                'description' => "Id pudo del destinatario del reso.  [Maxlegth=20]\nDato facoltativo. Se valorizzato returnShipmentConsigneePudoId, nel caso in cui l'indirizzo di consegna sia diverso dall'indirizzo del PUDO presente nell'anagrafica di BRT, la spedizione di reso viene creata correttamente al indirizzo del PUDO, ma l'esito del servizio restituisce un warning (5).",
            ],
        ];

        return $brtFields;
    }
}
