# modules/mpbrtapishipment/config/routes.yml

mpbrtapishipment_admin_bordero:
    path: /admin/brt/bordero
    defaults:
        _controller: 'MpSoft\MpBrtApiShipment\Controllers\Admin\Improve\AdminParentShipping\BrtBorderoController::showLastPendingBorderoAction'
        _legacy_controller: "AdminBrtBordero"
        _legacy_link: "AdminBrtBordero"

mpbrtapishipment_admin_printlabel:
    path: /admin/brt/printlabel/{id_bordero}
    defaults:
        _controller: 'MpSoft\MpBrtApiShipment\Controllers\Admin\Improve\AdminParentShipping\BrtBorderoController::printLabelAction'
        _legacy_controller: "AdminBrtBordero"
        _legacy_link: "AdminBrtBordero"

mpbrtapishipment_admin_getlabellink:
    path: /admin/brt/bordero/getLabelLink/{numericSenderReference}
    defaults:
        _controller: 'MpSoft\MpBrtApiShipment\Controllers\Admin\Improve\AdminParentShipping\BrtBorderoController::getLabelLinkAction'
        _legacy_controller: "AdminBrtBordero"
        _legacy_link: "AdminBrtBordero"
        _method: "GET"
    requirements:
        numericSenderReference: "/[0-9]+"
